# Generated by Django 4.1.1 on 2022-10-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='imag',
            new_name='image',
        ),
    ]
